"""Add name column to users table

Revision ID: 50e9af487599
Revises: e6811d9c3839
Create Date: 2025-03-15 00:42:37.321628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50e9af487599'
down_revision: Union[str, None] = 'e6811d9c3839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('token_data', sa.Text(), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'name')
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'token_data')
    op.drop_column('accounts', 'expires_at')
    op.drop_column('accounts', 'refresh_token')
    op.drop_column('accounts', 'access_token')
    # ### end Alembic commands ###
